### ISSUE TITLE
Recommended Approach: Creating GIfs

### ISSUE THREAD

**Issue by Btibert3** [the-bucketless/hockey_rink#1]
Your library is fantastic.  I have successfully built out a process that lets me run through a series of data and via `.scatter` I can plot the location of events.  The issue is that the build process is painfully slow.

I have attempted various solutions (cla, clf, ax.clear).  While some of my attempts certainly sped up the build, I lost the plot of the rink.  As you can likey tell from this question, I am not the most robust user of matplotlib.

This is not an issue with your library of course, but I am wondering if you have any recommendations on we might be able to use the rink, perhaps plot data via `.scatter`, and then clear out the scatter for the next "frame" being plotted.  I _believe_ that the slowness in the build process is due to re-drawing the rink, which is why I am wondering if you have any suggestions on how to draw the rink just once in a loop.

Cheers.

**Comment by the-bucketless** [comment]
Yeah, I found this too when I was making GIFs with the BDC data. You can see how I dealt with it [here](https://github.com/the-bucketless/bdc/blob/main/bdc_tracking_animation.ipynb).

Basically, you keep a global variable for the scatter object that you can .remove() at the start of each frame rather than re-drawing.

**Comment by Btibert3** [comment]
Great, thank you for the quick response.  This is very helpful.
